domain: .frock.aws.avalonconsult.net
config:
    importPath: /git/config/6.5/default/am/empty-import
image:
  repository: gcr.io/forgerock-io/amster


# config:
#   importPath: /git/config/6.0/identity-platform-examples/am-ds
#   exportPath: /tmp/amster

# version: 6.5.2

# For production set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 756Mi
 requests:
   memory: 756Mi

# Use the config store as the cts
# ctsStores: "configstore-0.configstore:1389"
