# ForgeOps gatling helm chart
# This is a YAML-formatted file.

# Domain on which reports will be available
# domain: .forgeops.com
domain: .k8s.aws.avalonconsult.net

# Gatling image with tests.
# Dockerfile for this image can be found in forgeops/docker/gatling
image:
  repository: gcr.io/forgerock-io/gatling:6.5.2
  pullPolicy: Always
  
gitImage:
  repository: gcr.io/forgerock-io/git
  tag: 6.5.2
  pullPolicy: IfNotPresent

config:
  # Name of the configMap that holds the configuration repository URL and of
  # the secret required to access it.
  name: frconfig
  # strategy defines how products get their configuration .
  # Using the git strategy, each helm chart pulls the configuration from git using an init container.
  strategy: git

taints:
  # Taint checking, turned off by default.
  enabled: false

benchmark:
  # Name of scala test name to run
  # This benchmark supports following testnames
  #   - am.AMRestAuthNSim
  #   - am.AMAccessTokenSim
  #
  # For IDM it is:
  # ( Always run Create test first to have users present for other tests)
  # - idm.IDMCreateManagedUsers
  # - idm.IDMReadManagedUsers
  # - idm.IDMUpdateManagedUsers
  # - idm.IDMDeleteManagedUsers
  #
  # For IG it is:
  # - ig.IGReverseProxyWebSim
  # 
  # To run multiple tests, syntax is as following:
  # testname: "am.AMAccessTokenSim am.AMRestAuthNSim"

  # testname: am.AMAccessTokenSim
  # testname: am.AMRestAuthNSim
  # testname: idm.IDMCreateManagedUsers
  tesname: ig.IGReverseProxyWebSim
  
  # By default, simulation will be run automatically after deployment.
  # Change to false force Gatling to wait for trigger.
  # To trigger simulation if false, add ready file to gatling init-container:
  # kubectl exec <podname> -c forgeops-benchmark-gatling touch /ready
  runAfterDeployment: true
  

  # How many users we want to use for benchmark
  users: "1000000"
  # How many user threads we want to use for benchmark
  concurrency: 50
  # Duration of test in seconds
  duration: 600
  # Logout percent in authn testnames(0 disables logout)
  logoutpercent: 0
  # Warmup duration
  warmup: 1
  # Token info - enables getting tokeninfo in AMAccessTokenSim tests
  get_token_info: "false"
  # Oauth2 client ID - Change to name of your OAuth2 client
  oauth2_client_id: "clientOIDC_0"
  oauth2_client_pw: "password"

  # Product specific values that are passed into gatling.
  # Will likely to expand in future to cover all 4 products.
  # In case you are running gatling in different namespace
  # you need to specify host as a full fqdn. e.g login.pyforge.forgeops.com 
  # and change proto to https
  openam:
    host: openam
    port: 80
    proto: http
  openidm:
    host: openidm
    port: 80
    proto: http
  openig:
    host: openig
    port: 80
    proto: http

# Reporting related values.
component: gatling
service:
  name: forgeops-benchmark
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  class: nginx
