# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
# Secrets for OpenIDM stack deployment.
# Note that secret values are base64-encoded.
apiVersion: v1
kind: Secret
metadata:
   name: "openidm-secrets-env"
type: Opaque
data:
   OPENIDM_ADMIN_PASSWORD: {{ default "openidm-admin" .Values.secret.openidmAdminPassword | b64enc }}
   OPENIDM_MIGRATION_URL: {{ default "https://idm.qa.ahadatahub.com/openidm/" .Values.idm.migration.url | b64enc }}
   OPENIDM_MIGRATION_ADMIN_USERNAME: {{ default "openidm-admin" .Values.idm.migration.adminUsername | b64enc }}
   OPENIDM_MIGRATION_ADMIN_PASSWORD: {{ default "openidm-admin" .Values.idm.migration.adminPassword | b64enc }}
