# Note if you enable TLS then you have to either provide the certificate 
# by running generate-tls.sh script or you have to have cert-manager deployed
# for your DNS domain 

#domain: .freng.org
# domain: .frk8s.net
# domain: .forgerock.k8s.aws.avalonconsult.net
# SSD: Note to self: don't add the namespace here...
domain: .k8s.aws.avalonconsult.net

#fqdn: login.small.freng.org
# fqdn: login.prod.frk8s.net
fqdn: login.prod.k8s.aws.avalonconsult.net
# SSD: Note to self - namespace above is OK.


# Install passwords.
amadminPassword: password
encryptionKey: "123456789012"
policyAgentPassword: Passw0rd
